# Generated by Django 5.1.7 on 2025-03-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
